# Generated by Django 5.0.1 on 2024-01-17 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24, verbose_name='제목')),
                ('photo', models.ImageField(blank=True, upload_to='posts/%Y%m%d')),
                ('content', models.CharField(max_length=24, verbose_name='내용')),
                ('region', models.CharField(max_length=24, verbose_name='지역')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.tool')),
            ],
        ),
    ]
