# Generated by Django 5.0.1 on 2024-01-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('genre', models.CharField(max_length=32)),
                ('ratings', models.CharField(max_length=32)),
            ],
        ),
    ]
