# Generated by Django 5.0.1 on 2024-01-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='content',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='year',
        ),
    ]
