# Generated by Django 5.0.1 on 2024-01-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_reviews_content_remove_reviews_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='reviews',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
